pub mod auth_service;
pub mod file_service;
pub mod frontmatter_service;
pub mod image_service;
pub mod markdown_service;
pub mod plugin_api;
pub mod plugin_runtime;
pub mod plugin_service;
pub mod search_service;
pub mod vault_service;
pub mod wiki_link_service;

pub use auth_service::AuthService;
pub use file_service::{FileService, RenameStrategy};
pub use image_service::ImageService;
pub use markdown_service::{MarkdownService, RenderOptions};
pub use plugin_api::{Command, Event, EventBus, EventType, PluginApi, PluginStorage};
pub use plugin_runtime::PluginRuntime;
pub use plugin_service::PluginService;
pub use search_service::SearchIndex;
pub use vault_service::VaultService;
pub use wiki_link_service::{FileIndex, ResolvedLink, WikiLinkResolver};
